### ISSUE TITLE
Assets\Script\PredictionMotor.cs(192,13): error CS0103: The name '_playerInput' does not exist in the current context

### ISSUE THREAD

**Issue by Freebase394** [RidefortGames/FishNet-ThirdPersonPrediction#1]
Hi there
If this mensage apears to you:
Assets\Script\PredictionMotor.cs(192,13): error CS0103: The name '_playerInput' does not exist in the current context
You need to add this to define SYMBOLS
![image](https://user-images.githubusercontent.com/19652056/167296654-d3ccd1a4-b20c-453d-8474-7e9be4c165d0.png)

**Comment by southglory** [comment]
![image](https://user-images.githubusercontent.com/51065570/230456727-e7cc6f4f-0ec3-4216-981a-4f85cb3f1a5c.png)

Hi, How to fix this error?
I imported 'fishnet_pro_3.5.8', 'Starter Assets - Third Person Character Controller', 'input_system 1.5.1', and this repo.

**Comment by KarlosEnd** [comment]
After adding the above I get this:

FishNet.CodeGenerating.ILCore.FishNetILPP: (0,0): error  - Replicate method Move within PredictionMotor requires exactly 4 parameters. In order: replicate data, asServer boolean, channel = Channel.Unreliable, replaying boolean.

FishNet.CodeGenerating.ILCore.FishNetILPP: (0,0): error  - Reconcile method Reconciliation within PredictionMotor requires exactly 3 parameters. In order: replicate data, asServer boolean, channel = Channel.Unreliable.

PostProcessing failed: Unity.ILPP.Runner.ILPostProcessorDiagnosticsException: FishNet.CodeGenerating.ILCore.FishNetILPP: (0,0): error  - Replicate method Move within PredictionMotor requires exactly 4 parameters. In order: replicate data, asServer boolean, channel = Channel.Unreliable, replaying boolean.

(0,0): error  - Reconcile method Reconciliation within PredictionMotor requires exactly 3 parameters. In order: replicate data, asServer boolean, channel = Channel.Unreliable.
   at Unity.ILPP.Runner.PostProcessingPipeline.HandleDiagnosticMessages(String ilppName, List`1 messageList, LoggerAndProgressSink& combinedLogger)
   at Unity.ILPP.Runner.PostProcessingPipeline.PostProcessAssemblyAsync(PostProcessAssemblyRequest request, Action`2 progressSink)
   at Unity.ILPP.Runner.PostProcessingService.PostProcessAssembly(PostProcessAssemblyRequest request, IServerStreamWriter`1 responseStream, ServerCallContext context)
Unhandled Exception: System.InvalidOperationException: Post processing failed
   at Unity.ILPP.Trigger.TriggerApp.<ProcessArgumentsAsync>d__1.MoveNext() + 0xf74
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at Unity.ILPP.Trigger.TriggerApp.<ProcessArgumentsAsync>d__1.MoveNext() + 0x1149
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Unity.ILPP.Trigger.TriggerApp.<RunAsync>d__0.MoveNext() + 0xc7
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Program.<<Main>$>d__0.MoveNext() + 0x1a3
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Program.<Main>(String[]) + 0x20
   at Unity.ILPP.Trigger!<BaseAddress>+0x47849b
